name: Daily Instagram Post

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: pip install --no-deps instagrapi==2.5.13 && pip install pycryptodomex pillow requests schedule python-dotenv pytrends httpx pydantic PySocks pytz
        shell: cmd

      - name: Create .env
        run: |
          echo GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}> .env
          echo IMGBB_API_KEY=${{ secrets.IMGBB_API_KEY }}>>.env
          echo INSTAGRAM_USERNAME=${{ secrets.INSTAGRAM_USERNAME }}>>.env
          echo INSTAGRAM_PASSWORD=${{ secrets.INSTAGRAM_PASSWORD }}>>.env
          echo POST_TIME=08:00>>.env
        shell: cmd

      - name: Run daily post
        run: python main.py --run-now > output.log 2>&1 & type output.log
        shell: cmd
        env:
          IG_SESSION_ID: ${{ secrets.IG_SESSION_ID }}

      - name: Show error log
        if: failure()
        run: type output.log
        shell: cmd
